[pytest]

# Test discovery
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Markers
markers =
    smoke: smoke test cases
    regression: regression test cases
    sanity: sanity test cases
    api: api test cases
    ui: ui test cases
    login: login related tests

# Command line options
addopts = -v --video=retain-on-failure --env=uat --reruns 2 --reruns-delay 2 --html=reports/report.html --self-contained-html

# Test folder
testpaths = tests

# Logging
log_cli = true
log_cli_level = INFO

# Warnings
filterwarnings =
    ignore::DeprecationWarning